"""add join token to units

Revision ID: 381e71bc2bbe
Revises: 09148463d34f
Create Date: 2026-03-24 02:26:43.054499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381e71bc2bbe'
down_revision = '09148463d34f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('join_link_enabled', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint('uq_unit_join_token', ['join_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_constraint('uq_unit_join_token', type_='unique')
        batch_op.drop_column('join_link_enabled')
        batch_op.drop_column('join_token')

    # ### end Alembic commands ###
