"""Rebrand user profile fields and terminology

Revision ID: 8400b033e47f
Revises: f43cbe4ef981
Create Date: 2026-03-25 13:06:09.288833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8400b033e47f'
down_revision = 'f43cbe4ef981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('rank', new_column_name='title')
        batch_op.alter_column('service_number', new_column_name='reference_id')
        batch_op.alter_column('division', new_column_name='department')
        batch_op.alter_column('trade', new_column_name='specialty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('title', new_column_name='rank')
        batch_op.alter_column('reference_id', new_column_name='service_number')
        batch_op.alter_column('department', new_column_name='division')
        batch_op.alter_column('specialty', new_column_name='trade')

    # ### end Alembic commands ###
