"""Add admin join token

Revision ID: a708171cf3cb
Revises: 381e71bc2bbe
Create Date: 2026-03-24 03:35:28.186164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a708171cf3cb'
down_revision = '381e71bc2bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_join_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('admin_join_link_enabled', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.create_unique_constraint('uq_unit_admin_join_token', ['admin_join_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_constraint('uq_unit_admin_join_token', type_='unique')
        batch_op.drop_column('admin_join_link_enabled')
        batch_op.drop_column('admin_join_token')

    # ### end Alembic commands ###
