"""add time format to unit

Revision ID: b37604880dd9
Revises: 8400b033e47f
Create Date: 2026-03-25 13:53:54.269107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37604880dd9'
down_revision = '8400b033e47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_format', sa.String(length=5), nullable=False, server_default='12h'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_column('time_format')

    # ### end Alembic commands ###
